on:
  pull_request:
  push:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        jre: [17]
        os: [ubuntu-latest, windows-latest]
        include:
          - jre: 21
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: git clone https://github.com/diffplug/durian-rx ../durian-rx
      - name: Install JDK ${{ matrix.jre }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.jre }}
      - name: gradle caching
        uses: gradle/actions/setup-gradle@v4
      - name: git fetch origin main
        run: git fetch origin main
      - name: gradlew build
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install xvfb
            Xvfb :99 &
            export DISPLAY=:99
          fi
          ./gradlew build --no-configuration-cache
        shell: bash
      - name: junit result
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step fails
        with:
          check_name: JUnit ${{ matrix.jre }} ${{ matrix.os }}
          report_paths: '*/build/test-results/*/TEST-*.xml'
